@isTest

public class CarroTest {

    @isTest
    static void testaacelerar(){
        Carro novoCarro = new Carro();
        Boolean acelerou = novoCarro.acelerar(10);
        system.assertEquals(acelerou, true);
    }

    @isTest
    static void testaacelerarCorreto(){
        Carro novoCarro = new Carro();
        novoCarro.modelo = 'Audi';
        novoCarro.cor = 'Amarelo';
        novoCarro.
        novoCarro.

    }

}

