public with sharing class ClasseEstruturaFeia {
    public static void metodo1(){
        Boolean bTrue = true;
        Boolean bFalse = false;
        Boolean bExemple;
        String exemploString = 'texto 123456';
        Integer exemploInteiro = 1;
        Decimal exemploDecimal = 1.02;
        Double exemploDouble = 1.0255464454546;
    }    

    public static void metodo2(){
        Boolean bTrue = true;
        Boolean bFalse = false;
        Boolean bExemple;
        String exemploString = 'texto 123456';
        Integer exemploInteiro = 1;
        Decimal exemploDecimal = 1.02;
        Double exemploDouble = 1.0255464454546;
    }    
    
    public static void metodo3(){
        Boolean bbol;
    }
}

    

